import React, { useState, useEffect, useRef } from "react";
import { CADResponse, LayoutDimensions } from "../types";
import { Compass, Code, Play, Copy, Check, Terminal, Sparkles, HelpCircle, HardDrive, Cpu, RefreshCw } from "lucide-react";

interface AutoCadAgentProps {
  initialPrompt?: string;
  gardenSizeSqm?: number;
}

export const AutoCadAgent: React.FC<AutoCadAgentProps> = ({
  initialPrompt = "",
  gardenSizeSqm = 120
}) => {
  const [requestText, setRequestText] = useState(
    initialPrompt || "תייצר תוכנית שתילה לגינה עם 5 עצי זית במרחקים של 3 מטרים ואמצעי תיאור מוגבהים"
  );
  
  // Custom design parameters
  const [width, setWidth] = useState(10);
  const [length, setLength] = useState(15);
  const [spacing, setSpacing] = useState(3.0);
  
  const [isLoading, setIsLoading] = useState(false);
  const [cadData, setCadData] = useState<CADResponse | null>(null);
  const [activeTab, setActiveTab] = useState<"lisp" | "python" | "instructions">("lisp");
  const [copied, setCopied] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  // Load default simulated CAD structure on first mount
  useEffect(() => {
    // Generate a default LISP layout on launch so they don't see an empty page
    const lispCode = generateMockLispLocal(width, length, spacing);
    setCadData(lispCode);
  }, []);

  // Whenever CAD dimensions or coordinates update, redraw our visual mockup in HTML5 Canvas
  useEffect(() => {
    drawCadBlueprint();
  }, [cadData, width, length, spacing]);

  const generateMockLispLocal = (w: number, l: number, sp: number): CADResponse => {
    const numTrees = Math.floor(l / sp);
    const lisp = `;========================================================================
; AutoLISP script generated by Landscape Automation Studio
; Description: Generates a grid layout for landscape architecture
; Parameters: Area ${w}m x ${l}m, Spacing ${sp}m
;========================================================================

(defun c:CREATE_GARDEN ( / pt width length spacing i pt_next)
  (setq old_cmdecho (getvar "cmdecho"))
  (setvar "cmdecho" 0)

  (alert "סייען האוטומציה יוצר כעת את הגינה במרחב העבודה שלך...")
  
  ; Prompt user for insertion point
  (setq pt (getpoint "\\nבחר נקודת התחלה לפינת הגינה: "))
  (if (null pt) (setq pt '(0.0 0.0 0.0)))
  
  (setq width ${w})
  (setq length ${l})
  (setq spacing ${sp})

  ; Create dedicated Design layers
  (command "-layer" "m" "L-BOUNDARY" "c" "4" "" "") ; Cyan for boundary
  (command "-layer" "m" "L-TREES" "c" "2" "" "")    ; Green for trees
  (command "-layer" "m" "L-LABELS" "c" "7" "" "")   ; White for text

  ; Draw Boundary Polyline
  (command "layer" "s" "L-BOUNDARY" "")
  (command "pline" 
    pt 
    (list (+ (car pt) width) (cadr pt) 0.0)
    (list (+ (car pt) width) (+ (cadr pt) length) 0.0)
    (list (car pt) (+ (cadr pt) length) 0.0)
    "c"
  )
  
  ; Draw main featured olive trees at intervals
  (command "layer" "s" "L-TREES" "")
  (setq i 1.5)
  (while (< i length)
    (setq pt_next (list (+ (car pt) (/ width 2.0)) (+ (cadr pt) i) 0.0))
    
    ; Draw Olive tree representation (Circle inside secondary circle)
    (command "circle" pt_next 0.6)
    (command "circle" pt_next 0.15)
    
    ; Add dynamic node index labels
    (command "layer" "s" "L-LABELS" "")
    (command "text" "j" "mc" (list (car pt_next) (+ (cadr pt_next) 1.0) 0.0) 0.3 0.0 (strcat "Olive Tree - " (rtos i 2 0) "m"))
    (command "layer" "s" "L-TREES" "")
    
    (setq i (+ i spacing))
  )

  (setvar "cmdecho" old_cmdecho)
  (princ "\\n========================================\\n")
  (princ "\\n[תוכנית הגינה נוצרה בהצלחה! השתמש בפקודה CREATE_GARDEN]")
  (princ "\\n========================================\\n")
  (princ)
)
`;

    const python = `import sys
try:
    import pyautocad
    from pyautocad import Autocad, APoint
    
    acad = Autocad(create_if_not_exists=True)
    acad.prompt("AutoCAD Python layout builder started\\n")
    
    width = ${w}
    length = ${l}
    spacing = ${sp}
    
    # Establish boundary coordinates
    acad.model.AddLine(APoint(0,0), APoint(width, 0))
    acad.model.AddLine(APoint(width, 0), APoint(width, length))
    acad.model.AddLine(APoint(width, length), APoint(0, length))
    acad.model.AddLine(APoint(0, length), APoint(0,0))
    
    # Generate tree arrays
    y = 1.5
    while y < length:
        acad.model.AddCircle(APoint(width / 2.0, y), 0.6)
        acad.model.AddMText(APoint(width / 2.0, y + 0.8), 0.3, "Olive Tree")
        y += spacing
except Exception as e:
    print("PyAutoCAD environment error:", e)
`;

    return {
      commandShortcut: "CREATE_GARDEN",
      lispCode: lisp,
      pythonEquivalent: python,
      instructionsHe: "הוראות הרצה באוטוקאד:\n1. שמור את קוד ה-LISP כקובץ בשם 'garden.lsp'\n2. בתוך אוטוקאד, הקלד APPLOAD וטען את הקובץ\n3. הקלד את הפקודה CREATE_GARDEN, הגינה והצמחים ייווצרו מיידית בשכבות נפרדות!",
      instructionsEn: "AutoCAD Run manual:\n1. Save the code into a garden.lsp file.\n2. Load it utilizing standard 'APPLOAD' command.\n3. Run 'CREATE_GARDEN' command keys.",
      cadElementsCount: {
        boundaries: 1,
        trees: numTrees,
        shrubs: 2,
        utilityAndLabels: numTrees + 2
      }
    };
  };

  const drawCadBlueprint = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const canvasWidth = canvas.width;
    const canvasHeight = canvas.height;

    // Clear Canvas and Draw Dark Blueprint AutoCAD Grid Background
    ctx.fillStyle = "#0c1524"; // Charcoal dark CAD blue
    ctx.fillRect(0, 0, canvasWidth, canvasHeight);

    // Draw grid lines
    ctx.lineWidth = 0.5;
    ctx.strokeStyle = "#172b43"; // Grid lines
    const gridSize = 25;
    for (let x = 0; x < canvasWidth; x += gridSize) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, canvasHeight);
      ctx.stroke();
    }
    for (let y = 0; y < canvasHeight; y += gridSize) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(canvasWidth, y);
      ctx.stroke();
    }

    // Crosshair in center
    ctx.strokeStyle = "#243e62";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(canvasWidth / 2, 0);
    ctx.lineTo(canvasWidth / 2, canvasHeight);
    ctx.moveTo(0, canvasHeight / 2);
    ctx.lineTo(canvasWidth, canvasHeight / 2);
    ctx.stroke();

    // Map garden dimensions (Width & Length in meters) to pixel margins
    // Set padding of 40px in each direction
    const padding = 50;
    const maxDrawWidth = canvasWidth - padding * 2;
    const maxDrawHeight = canvasHeight - padding * 2;

    // Determine ratios
    const scaleX = maxDrawWidth / width;
    const scaleY = maxDrawHeight / length;
    const scale = Math.min(scaleX, scaleY);

    // Calculate actual pixel size of our garden rectangle
    const drawW = width * scale;
    const drawH = length * scale;

    // Outer garden bounds center align offset
    const startX = (canvasWidth - drawW) / 2;
    const startY = (canvasHeight - drawH) / 2;

    // Draw outer garden bound (Cyan - Layer: L-BOUNDARY)
    ctx.strokeStyle = "#00ffff"; // Cyan
    ctx.lineWidth = 2.5;
    ctx.strokeRect(startX, startY, drawW, drawH);

    // Draw dimensions text label helpers
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 11px Inter, system-ui";
    ctx.textAlign = "center";
    ctx.fillText(`${width}m (ציר X)`, startX + drawW / 2, startY - 10);
    
    // Y-axis dimensions text vertical rendering
    ctx.save();
    ctx.translate(startX - 15, startY + drawH / 2);
    ctx.rotate(-Math.PI / 2);
    ctx.fillText(`${length}m (ציר Y)`, 0, 0);
    ctx.restore();

    // Draw trees arrays on standard Grid structure (Layer: L-TREES) - centered on X
    const treeRadius = 0.6 * scale; // 0.6m tree symbol diameter
    const innerTreeRadius = 0.15 * scale;
    const spacingPx = spacing * scale;
    const centerX_Px = startX + drawW / 2;

    let treeY = 1.5; // Starts at 1.5 meters high
    let treeCount = 0;

    ctx.fillStyle = "#22c55e"; // Sage green for plant layer
    ctx.strokeStyle = "#4ade80"; // Bright green boundary
    ctx.lineWidth = 1.5;

    while (treeY < length) {
      const treeY_Px = startY + (length - treeY) * scale; // Flip Y (standard CAD directions)

      // Draw custom tree symbol
      ctx.beginPath();
      ctx.arc(centerX_Px, treeY_Px, treeRadius, 0, Math.PI * 2);
      ctx.stroke();

      ctx.beginPath();
      ctx.arc(centerX_Px, treeY_Px, innerTreeRadius, 0, Math.PI * 2);
      ctx.fillStyle = "#166534";
      ctx.fill();
      ctx.stroke();

      // Small crown spokes
      for (let angle = 0; angle < Math.PI * 2; angle += Math.PI / 4) {
        ctx.beginPath();
        ctx.moveTo(centerX_Px, treeY_Px);
        ctx.lineTo(
          centerX_Px + Math.cos(angle) * treeRadius,
          treeY_Px + Math.sin(angle) * treeRadius
        );
        ctx.stroke();
      }

      // Layer annotation tags (L-LABELS)
      ctx.fillStyle = "#ffffff";
      ctx.font = "9px monospace";
      ctx.textAlign = "left";
      ctx.fillText(`Olive-${treeCount + 1}`, centerX_Px + treeRadius + 6, treeY_Px + 3);

      treeY += spacing;
      treeCount++;
    }

    // Shrubs representation (Groups)
    ctx.fillStyle = "#10b981"; // Emerald
    ctx.strokeStyle = "#34d399";
    const shrubRadius = 0.3 * scale;
    const shrub1_X = startX + drawW * 0.2;
    const shrub1_Y = startY + drawH * 0.8;
    const shrub2_X = startX + drawW * 0.8;
    const shrub2_Y = startY + drawH * 0.8;

    // Draw Group A
    ctx.beginPath();
    ctx.arc(shrub1_X, shrub1_Y, shrubRadius, 0, Math.PI * 2);
    ctx.fill();
    ctx.stroke();
    ctx.fillStyle = "#ffffff";
    ctx.fillText("Group A", shrub1_X + shrubRadius + 4, shrub1_Y + 3);

    // Draw Group B
    ctx.fillStyle = "#10b981";
    ctx.beginPath();
    ctx.arc(shrub2_X, shrub2_Y, shrubRadius, 0, Math.PI * 2);
    ctx.fill();
    ctx.stroke();
    ctx.fillStyle = "#ffffff";
    ctx.fillText("Group B", shrub2_X + shrubRadius + 4, shrub2_Y + 3);

    // Compass visual north indicator
    ctx.strokeStyle = "#ef4444"; // Red north pointer
    ctx.lineWidth = 1.5;
    const compassX = canvasWidth - 45;
    const compassY = 45;
    ctx.beginPath();
    ctx.moveTo(compassX, compassY - 15);
    ctx.lineTo(compassX - 6, compassY + 10);
    ctx.lineTo(compassX + 6, compassY + 10);
    ctx.closePath();
    ctx.stroke();
    ctx.fillStyle = "#ef4444";
    ctx.fill();
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 9px monospace";
    ctx.fillText("N", compassX - 3, compassY - 18);

    // Scale metric helper in bottom right
    ctx.strokeStyle = "#ffffff";
    ctx.lineWidth = 1.5;
    const barW = 3 * scale; // 3 meters bar
    const barX = canvasWidth - 110;
    const barY = canvasHeight - 25;
    ctx.beginPath();
    ctx.moveTo(barX, barY - 4);
    ctx.lineTo(barX, barY);
    ctx.lineTo(barX + barW, barY);
    ctx.lineTo(barX + barW, barY - 4);
    ctx.stroke();
    ctx.fillText("קנ&quot;מ 3 מטר", barX + barW / 2 - 15, barY - 6);
  };

  const generateAILisp = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!requestText.trim()) return;

    setIsLoading(true);
    setCopied(false);

    try {
      const response = await fetch("/api/autocad/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          requestText,
          gardenDimensions: {
            width,
            length,
            spacing
          },
          selectedPlants: ["עץ זית מעוצב", "לבנדר", "שיחים"]
        }),
      });

      if (!response.ok) {
        throw new Error("שגיאה ביצירת סקריפט אוטוקאד בשרת");
      }

      const returnedCode: CADResponse = await response.json();
      setCadData(returnedCode);
    } catch (err: any) {
      console.error(err);
      alert(err.message || "שגיאה זמנית בפילוס סקיצות CAD מול בשרת");
    } finally {
      setIsLoading(false);
    }
  };

  const copyToClipboard = () => {
    if (!cadData) return;
    const contentToCopy = activeTab === "lisp" ? cadData.lispCode : cadData.pythonEquivalent || "";
    navigator.clipboard.writeText(contentToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-8 animate-fade-in text-stone-800" dir="rtl">
      
      {/* CAD Step Header Banner */}
      <div className="bg-gradient-to-l from-slate-900 to-slate-950 rounded-3xl p-6 sm:p-8 text-white shadow-xl relative overflow-hidden border border-slate-800">
        <div className="absolute right-0 bottom-0 opacity-15 pointer-events-none transform translate-x-16 translate-y-16">
          <Terminal className="w-96 h-96 text-cyan-400" />
        </div>
        <div className="relative z-10 max-w-3xl">
          <span className="inline-flex items-center gap-1 bg-cyan-500/20 text-cyan-300 text-xs px-3 py-1 rounded-full font-semibold mb-3 border border-cyan-500/30">
            <Cpu className="w-3.5 h-3.5 animate-spin" /> שלב ב&apos;: AutoCAD Integration Workspace
          </span>
          <h2 className="text-2xl sm:text-3xl font-black">סוכן קוד AI לאוטוקאד (AutoCAD Agent)</h2>
          <p className="text-slate-300 mt-2 text-sm sm:text-base leading-relaxed">
            מתרגם הנחיות בשפה חופשית לקוד <span className="font-semibold text-cyan-300 font-mono">AutoLISP</span> או <span className="font-semibold text-cyan-300 font-mono">CAD Python</span> מוכן להרצה. הצייר הווטוריאלי מסנכרן את הפרוגרמה לשרטוט, ובכך חוסך את זמני פתיחת הקבצים ומקצר תהליכי שירטוט מורכבים.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-8">
        
        {/* Left Side: Parameters Form and CAD Prompt Input */}
        <div className="bg-white rounded-3xl border border-stone-200 p-6 shadow-sm space-y-6">
          <h3 className="text-base font-bold text-stone-900 pb-3 border-b border-stone-100 flex items-center gap-2">
            <Compass className="w-5 h-5 text-emerald-600" />
            פרמטרי שרטוט והזנת פקודת AI
          </h3>

          <form onSubmit={generateAILisp} className="space-y-5">
            {/* Quick Geometric inputs */}
            <div className="grid grid-cols-3 gap-3 bg-stone-50 p-4 rounded-2xl border border-stone-100">
              <div>
                <label className="block text-[11px] font-bold text-stone-500 mb-1">רוחב גינה (X מטרים)</label>
                <input
                  type="number"
                  min="3"
                  max="100"
                  value={width}
                  onChange={(e) => setWidth(Number(e.target.value))}
                  className="w-full text-xs font-mono rounded-lg border border-stone-200 bg-white p-2 text-center text-stone-800 focus:outline-none focus:ring-1 focus:ring-emerald-500"
                />
              </div>
              <div>
                <label className="block text-[11px] font-bold text-stone-500 mb-1">אורך גינה (Y מטרים)</label>
                <input
                  type="number"
                  min="3"
                  max="100"
                  value={length}
                  onChange={(e) => setLength(Number(e.target.value))}
                  className="w-full text-xs font-mono rounded-lg border border-stone-200 bg-white p-2 text-center text-stone-800 focus:outline-none focus:ring-1 focus:ring-emerald-500"
                />
              </div>
              <div>
                <label className="block text-[11px] font-bold text-stone-500 mb-1">מרחקי שתילת עצים (מ&apos;)</label>
                <input
                  type="number"
                  step="0.5"
                  min="1"
                  max="20"
                  value={spacing}
                  onChange={(e) => setSpacing(Number(e.target.value))}
                  className="w-full text-xs font-mono rounded-lg border border-stone-200 bg-white p-2 text-center text-stone-800 focus:outline-none focus:ring-1 focus:ring-emerald-500"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold text-stone-700 mb-1.5 leading-relaxed">
                מה ברצונך שהסוכן יצייר? (הנחיה חופשית לקוד AutoCAD)
              </label>
              <textarea
                required
                rows={4}
                value={requestText}
                onChange={(e) => setRequestText(e.target.value)}
                placeholder="למשל: תייצר גינת פריסה מלבנית עם שכבות צד, רדיוס שתילת עצי זית לאורך הציר המרכזי וקבוצת שיחים פינתיים..."
                className="w-full rounded-xl border border-stone-200 p-3.5 text-xs text-stone-800 focus:ring-2 focus:ring-emerald-500 focus:outline-none placeholder:text-stone-400 leading-relaxed"
              />
            </div>

            <div className="flex justify-end gap-2">
              <button
                type="submit"
                disabled={isLoading}
                className="bg-slate-900 hover:bg-slate-950 text-white font-bold text-xs px-5 py-3.5 rounded-xl shadow-md transition-all flex items-center gap-2 cursor-pointer disabled:opacity-50"
              >
                {isLoading ? (
                  <>
                    סוכן AutoCAD מחשב...
                    <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                  </>
                ) : (
                  <>
                    מחולל סקריפטים עם AI
                    <Sparkles className="w-3.5 h-3.5 text-cyan-400" />
                  </>
                )}
              </button>
            </div>
          </form>

          {/* Interactive AutoCAD dark blueprint render preview block */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-stone-800 flex items-center gap-1">
                <Terminal className="w-4 h-4 text-emerald-600" /> סימולטור ווקטורי AutoCAD
              </span>
              <span className="text-[10px] bg-slate-950 text-cyan-400 font-mono px-2 py-0.5 rounded border border-slate-800">
                L-BOUNDARY: Cyan | L-TREES: Green
              </span>
            </div>
            
            <div className="relative rounded-2xl overflow-hidden border-2 border-slate-900 shadow-inner">
              <canvas
                ref={canvasRef}
                width={500}
                height={320}
                className="w-full block"
                title="AutoCAD Blueprint Vector Simulation"
              />
              <div className="absolute bottom-3 left-3 bg-slate-950/90 text-[10px] text-stone-400 p-2 rounded border border-slate-800 font-mono space-y-0.5">
                <div>COMMANDS: LISP C:{cadData?.commandShortcut || "CREATE_GARDEN"}</div>
                <div>Y-GRID Trees: {cadData?.cadElementsCount.trees || 0} Olive entities</div>
              </div>
            </div>
          </div>
        </div>

        {/* Right Side: Tabbed Code output box */}
        <div className="bg-slate-950 text-slate-100 rounded-3xl border border-slate-800 shadow-xl overflow-hidden flex flex-col justify-between">
          <div>
            {/* Tabs */}
            <div className="bg-slate-900 px-4 py-2 border-b border-slate-800 flex items-center justify-between">
              <div className="flex gap-1">
                <button
                  onClick={() => setActiveTab("lisp")}
                  className={`px-3 py-2 text-xs font-semibold rounded-lg transition-all cursor-pointer ${
                    activeTab === "lisp" ? "bg-slate-850 text-cyan-400 border border-slate-800" : "text-slate-400 hover:text-slate-200"
                  }`}
                >
                  <Code className="w-3.5 h-3.5 inline mr-1" />
                  AutoLISP Code (.lsp)
                </button>
                <button
                  onClick={() => setActiveTab("python")}
                  className={`px-3 py-2 text-xs font-semibold rounded-lg transition-all cursor-pointer ${
                    activeTab === "python" ? "bg-slate-850 text-cyan-400 border border-slate-800" : "text-slate-400 hover:text-slate-200"
                  }`}
                >
                  <Code className="w-3.5 h-3.5 inline mr-1" />
                  AutoCAD Python
                </button>
                <button
                  onClick={() => setActiveTab("instructions")}
                  className={`px-3 py-2 text-xs font-semibold rounded-lg transition-all cursor-pointer ${
                    activeTab === "instructions" ? "bg-slate-850 text-cyan-400 border border-slate-800" : "text-slate-400 hover:text-slate-200"
                  }`}
                >
                  <HelpCircle className="w-3.5 h-3.5 inline mr-1" />
                  הסבר הרצה במשרד
                </button>
              </div>

              {cadData && (
                <button
                  onClick={copyToClipboard}
                  className="bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white px-3 py-1.5 rounded-lg text-[11px] font-semibold transition-all flex items-center gap-1 cursor-pointer"
                >
                  {copied ? (
                    <>
                      הועתק! <Check className="w-3.5 h-3.5 text-emerald-400" />
                    </>
                  ) : (
                    <>
                      העתק קוד <Copy className="w-3.5 h-3.5" />
                    </>
                  )}
                </button>
              )}
            </div>

            {/* Code Content Block */}
            <div className="p-5 font-mono text-xs leading-relaxed max-h-[460px] overflow-y-auto">
              {isLoading ? (
                <div className="flex flex-col items-center justify-center py-24 text-slate-400 space-y-3">
                  <RefreshCw className="w-8 h-8 text-cyan-400 animate-spin" />
                  <span>סוכן ה-AI מחולל כעת סגמנטציית AutoLISP נקייה...</span>
                </div>
              ) : cadData ? (
                activeTab === "lisp" ? (
                  <pre className="text-emerald-400 whitespace-pre-wrap font-mono scrollbar-thin scrollbar-thumb-slate-800">
                    {cadData.lispCode}
                  </pre>
                ) : activeTab === "python" ? (
                  <pre className="text-cyan-400 whitespace-pre-wrap font-mono scrollbar-thin scrollbar-thumb-slate-800">
                    {cadData.pythonEquivalent || "PyAutoCAD script not generated."}
                  </pre>
                ) : (
                  <div className="text-slate-300 font-sans leading-relaxed space-y-4">
                    <h4 className="text-sm font-bold text-white">הוראות הרצה מפורטות באוטוקאד:</h4>
                    <pre className="text-slate-400 whitespace-pre-wrap font-sans text-xs bg-slate-900 p-4 rounded-xl border border-slate-850">
                      {cadData.instructionsHe}
                    </pre>
                    <div className="text-slate-500 text-[11px] pt-2 border-t border-slate-900 font-mono">
                      {cadData.instructionsEn}
                    </div>
                  </div>
                )
              ) : (
                <div className="text-slate-400 text-center py-24 text-sm font-sans">
                  טען או הזן מימדי גינה ולחץ על &quot;מחולל סקריפטים עם AI&quot; להפקת תבנית LISP דמו
                </div>
              )}
            </div>
          </div>

          {/* Infrastructure status footer inside code block */}
          <div className="bg-slate-900 border-t border-slate-800 p-4 flex items-center justify-between text-[11px] text-slate-500 font-mono">
            <span className="flex items-center gap-1">
              <span className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse"></span>
              CAD ENGINE READY
            </span>
            <span>PROPOSED COMMAND: {cadData?.commandShortcut || "CREATE_GARDEN"}</span>
          </div>

        </div>

      </div>

    </div>
  );
};
